// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCA-CmLxueSzyrEMnnPXyIiKSEvR5mc2AI',
    appId: '1:403509884500:web:49ff4e8746ab9804f9dfc1',
    messagingSenderId: '403509884500',
    projectId: 'figurestore-68028',
    authDomain: 'figurestore-68028.firebaseapp.com',
    storageBucket: 'figurestore-68028.firebasestorage.app',
    measurementId: 'G-446EWC7FLK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB49F4Q4JPhjOCsz7JdHhQ1alSFitT2HPw',
    appId: '1:403509884500:android:6e9edc5abf270b6bf9dfc1',
    messagingSenderId: '403509884500',
    projectId: 'figurestore-68028',
    storageBucket: 'figurestore-68028.firebasestorage.app',
  );

}